language: java
java : "8"

sudo: required

# 使用安全列表指定要构建的分支
branches:
  only:
  - master
  - dev
  - stable

cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
services:
- docker

script:
  - mvn test -DargLine="-Dspring.profiles.active=test" -Djasypt.encryptor.password="$ENCRYP_PASSWORD"
  - mvn clean package -Djasypt.encryptor.password="$ENCRYP_PASSWORD"

addons:
  ssh_known_hosts:
   - $HOST

before_install:
  - sudo apt-get update
  - sudo apt-get install sshpass

after_success:

  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.cn-qingdao.aliyuncs.com
  - docker build --build-arg key="$ENCRYP_PASSWORD" --build-arg java_file=./target/zealsay-1.0.0.jar -t registry.cn-qingdao.aliyuncs.com/zealsay/zealsay_backend:latest .
  - docker push registry.cn-qingdao.aliyuncs.com/zealsay/zealsay_backend:latest;


