debug: false

server:
  port: 8090

spring:
  profiles:
    active: dev
  application:
    name: zealsay
  main:
    allow-bean-definition-overriding: true #当遇到相同的名字，是否允许覆盖
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 123
            client-secret: 123



jwt:
  header: Authorization
  secret: ENC(rNbHP0gg31+MEI+EgAlZlQ==)
  expiration: 604800
  tokenHead: "Bearer "

swagger:
  basic:
    ## 开启Swagger的Basic认证功能,默认是false
    enable: true
    ## Basic认证用户名
    username: zealsay
    ## Basic认证密码
    password: api123456


mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mappings/*Mapper.xml
  mapper-locations: classpath:/mappings/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.pilipa.notification.entity
  global-config:
    banner: false
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    # sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    # meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

ignore:
  urls:
      - /api/v1/authentication/login
      - /api/v1/authentication/require
      - /api/v1/authentication/logout
      - /api/v1/service/hitokoto
      - /api/v1/article/c/page
      - /api/v1/article/category
      - /api/v1/article/label/page
      - /api/v1/article/*
      - /**/*.css
      - /social
      - /signin
      - /signup
      - /info
      - /health
      - /metrics/**
      - /loggers/**
      - /mobile/token
      - /v2/**
      - /webjars/**
      - /swagger-resources
      - /doc.html

---
spring:
  profiles: prod
  redis:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
    port: 6379
  rabbitmq:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
  datasource:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(E190EwXhkbGxHcPBWhVz6Q==)
    password: ENC(vB31HVjy7jKr2CzL57DEp7AfEnJslkmN)
    url: jdbc:mysql://${spring.datasource.host}/zealsay?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
#    password: ENC(bdIOy20mX8QA2TZwsAF0SdguRKrw3TQo)
#  data:
#    mongodb:
#      host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
#      port: 27017
#      database: zealsay
#      username: ENC(u6vRkpDKX567sw/j8nAPjQ==)
#      password: ENC(0WMifrrUxCi9dOgrn9mG17X6yxsjt14B)
#      authentication-database: admin
qiniu:
  Domain: https://pan.zealsay.com/
  Bucket: ENC(+qiMEWIsExb2bCJ/+FeFAfFuTLkaFeMh)
  AccessKey: ENC(AnoQmoYGtHaw3J/Tdp9SVb9Gr0Gcl69bsCY0cDlqHUGD0mxt9FlGjvEXCB5qfqyDbNulQaZoROw=)
  SecretKey: ENC(4sy78avC7S3AcP4uwOdmIMmQV1AM5ifwjhvvgSKIdfwlFJeEuUn0iRvoXFmsumYUwDSlb7mk2V8=)

---
spring:
  profiles: dev
  redis:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
    port: 6379
#    password: ENC(y/Q+pGasSBO27pTJlSNjkVtTgoENZAqK)
  rabbitmq:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
  datasource:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(3zTmw6RzYlG2qbF2aTNqtFSliUcqegme)
    password: ENC(NqsKPIk2YHaKz4IILon++nEYdyUaGdHn)
    url: jdbc:mysql://${spring.datasource.host}:3306/zealsay_svt?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
qiniu:
  Domain: https://pic.zealsay.com/
  Bucket: ENC(URCSSAswx1fYpIxBXzMkmHi8XGVAxqrXL0OXy4w1y+I=)
  AccessKey: ENC(l7FGA3cDMF91mw0Pahc0TO0thE0sXz4C07Ha41tYQkzKAt4hgoF4hLJzmgM8NkK/IPMG8hbDR10=)
  SecretKey: ENC(ptJFuHYe8PtaP+i64Vu+D6QiEUgc+zeTGjzp+d57gn9jtIAJsFwjLLK0IxsmdnN+yma86BmbpF8=)

---
spring:
  profiles: test
  redis:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
    port: 6379
#    password: ENC(cax30dcK4hlSyUXvCtTMTDhkczbSTduh)
  rabbitmq:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
  datasource:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(uvPCQE8yRpcGZfNrtvZUGQ==)
    password: ENC(ipXR4HFMaykv+IdxyLxx+I9LqtgN7pnX)
    url: jdbc:mysql://${spring.datasource.host}:3306/zealsay?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
