spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
    timeout: 10000
  datasource:
    host: localhost
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zeal
    password: 123456
    url: jdbc:mysql://${spring.datasource.host}:3306/zealsay_admin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  mail:
    host: smtp.mxhichina.com
    username: zeal@zealsay.com
    password: xxx
    default-encoding: UTF-8

web:
  name: zealsay说你想说
  domain: http://localhost:4000/
  default:
    password: $2a$10$DmMktUppa9g.qWPmGPOM/.VQGP0Njrf09vC3FIbNp2G91R1Xdq466

qiniu:
  Domain: https://pic.zealsay.com/
  Bucket: xxx
  AccessKey: xxx
  SecretKey: xxx

swagger:
  basic:
    ## 开启Swagger的Basic认证功能,默认是false
    enable: true
    ## Basic认证用户名
    username: zealsay
    ## Basic认证密码
    password: api123456

justauth:
  enabled: true
  type:
    github:
      client-id: xxx
      client-secret: xxx
      redirect-uri: http://localhost:8090/api/v1/oauth/github/callback
  cache:
    type: default
