debug: false

server:
  port: 8090
  jetty:
    acceptors: 2 #Jetty的线程架构模型非常简单，分为acceptors，selectors和workers三个线程池。acceptors负责接受新连接，然后交给selectors处理
    selectors: 4

spring:
  profiles:
    active: dev
  application:
    name: zealsay
  main:
    allow-bean-definition-overriding: true #当遇到相同的名字，是否允许覆盖
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 123
            client-secret: 123



jwt:
  header: Authorization
  secret: ENC(rNbHP0gg31+MEI+EgAlZlQ==)
  expiration: 604800
  tokenHead: "Bearer "

swagger:
  basic:
    ## 开启Swagger的Basic认证功能,默认是false
    enable: true
    ## Basic认证用户名
    username: zealsay
    ## Basic认证密码
    password: api123456


mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mappings/*Mapper.xml
  mapper-locations: classpath:/mappings/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.pilipa.notification.entity
  global-config:
    banner: false
    db-config:
      #驼峰下划线转换
      table-underline: true
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: mp_
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      # sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      #字段验证策略之 insert 默认NOT_NULL
      insert-strategy: default
      #字段验证策略之 update 默认NOT_NULL
      update-strategy: not_null
      #字段验证策略之 select 默认NOT_NULL
      select-strategy: default
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

ignore:
  urls:
    - /api/v1/authentication/login
    - /api/v1/authentication/require
    - /api/v1/authentication/logout
    - /api/v1/oauth/**
    - /api/v1/service/hitokoto
    - /api/v1/article/c/page
    - /api/v1/article/category
    - /api/v1/article/label/page
    - /api/v1/article/read/*
    - /api/v1/article/*
    - /api/v1/friend/link/page
    - /api/v1/user/use/username/*
    - /api/v1/user/use/email/*
    - /api/v1/user/register/email
    - /api/v1/user/confirm/email
    - /api/v1/user/register
    - /**/*.css
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /mobile/token
    - /v2/**
    - /webjars/**
    - /swagger-resources
    - /doc.html

---
spring:
  profiles: prod
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: 10000
  rabbitmq:
    host: ${MQ_HOST}
  datasource:
    host: ${MYSQL_HOST}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${spring.datasource.host}/zealsay?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  mail:
    host: smtp.mxhichina.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
#    password: ENC(bdIOy20mX8QA2TZwsAF0SdguRKrw3TQo)
#  data:
#    mongodb:
#      host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
#      port: 27017
#      database: zealsay
#      username: ENC(u6vRkpDKX567sw/j8nAPjQ==)
#      password: ENC(0WMifrrUxCi9dOgrn9mG17X6yxsjt14B)
#      authentication-database: admin
qiniu:
  Domain: ${QINIU_DOMAIN}
  Bucket: ${QINIU_BUCKET}
  AccessKey: ${QINIU_ACCESSKEY}
  SecretKey: ${QINIU_SECRETKEY}

web:
  name: zealsay说你想说
  domain: https://blog.zealsay.com/
  default:
    password: $2a$10$DmMktUppa9g.qWPmGPOM/.VQGP0Njrf09vC3FIbNp2G91R1Xdq466

justauth:
  enabled: true
  type:
    github:
      client-id: ENC(2Yn+IGbaGgy7l9lZIIfTHzBoSAT9PRsqUv7BjBJ7RaA=)
      client-secret: ENC(IqKWhEX8c35fmdFtcTtxPpB9OCmHb6KDd12k647+lSM2Wo7Xz6isevkl5PegKvF+FC0Zc7xYebI=)
      redirect-uri: https://api.zealsay.com/api/v1/oauth/github/callback
  cache:
    type: default
---
spring:
  profiles: dev
  redis:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
    port: 6379
    timeout: 10000
  #    password: ENC(y/Q+pGasSBO27pTJlSNjkVtTgoENZAqK)
  rabbitmq:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
  datasource:
    host: ENC(nDflcjbxkjqqTe5hDsnUkx5wBjMqhPcX)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(3zTmw6RzYlG2qbF2aTNqtFSliUcqegme)
    password: ENC(NqsKPIk2YHaKz4IILon++nEYdyUaGdHn)
    url: jdbc:mysql://${spring.datasource.host}:3306/zealsay_svt?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  mail:
    host: smtp.mxhichina.com
    username: ENC(QANq/D7pvRn7jN4RXMo4RBFrHDk4HyWnHlxKKhcifpU=)
    password: ENC(qz4bO/hrEYHjPZYb2YuWfDnWD1zADgO/)
    default-encoding: UTF-8

web:
  name: zealsay说你想说
  domain: http://localhost:8080/
  default:
    password: $2a$10$DmMktUppa9g.qWPmGPOM/.VQGP0Njrf09vC3FIbNp2G91R1Xdq466

qiniu:
  Domain: https://pic.zealsay.com/
  Bucket: ENC(URCSSAswx1fYpIxBXzMkmHi8XGVAxqrXL0OXy4w1y+I=)
  AccessKey: ENC(l7FGA3cDMF91mw0Pahc0TO0thE0sXz4C07Ha41tYQkzKAt4hgoF4hLJzmgM8NkK/IPMG8hbDR10=)
  SecretKey: ENC(ptJFuHYe8PtaP+i64Vu+D6QiEUgc+zeTGjzp+d57gn9jtIAJsFwjLLK0IxsmdnN+yma86BmbpF8=)

justauth:
  enabled: true
  type:
    github:
      client-id: ENC(2Yn+IGbaGgy7l9lZIIfTHzBoSAT9PRsqUv7BjBJ7RaA=)
      client-secret: ENC(IqKWhEX8c35fmdFtcTtxPpB9OCmHb6KDd12k647+lSM2Wo7Xz6isevkl5PegKvF+FC0Zc7xYebI=)
      redirect-uri: http://localhost:8090/api/v1/oauth/github/callback
  cache:
    type: default

---
spring:
  profiles: test
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
  #    password: ENC(cax30dcK4hlSyUXvCtTMTDhkczbSTduh)
  rabbitmq:
    host: 127.0.0.1
  datasource:
    host: 127.0.0.1
    driver-class-name: org.h2.Driver
    username: test
    password: test
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  mail:
    host: smtp.mxhichina.com
    username: xxx@zealsay.com
    password: 123
    default-encoding: UTF-8

jwt:
  header: Authorization
  secret: 123
  expiration: 604800
  tokenHead: "Bearer "


web:
  name: zealsay说你想说
  domain: https://blog.zealsay.com/
  default:
    password: $2a$10$DmMktUppa9g.qWPmGPOM/.VQGP0Njrf09vC3FIbNp2G91R1Xdq466

qiniu:
  Domain: https://pic.zealsay.com/
  Bucket: 123
  AccessKey: 123
  SecretKey: 123

justauth:
  enabled: true
  type:
    github:
      client-id: 123
      client-secret: 123
      redirect-uri: https://api.zealsay.com/api/v1/oauth/github/callback
  cache:
    type: default