debug: false

server:
  port: 8090

spring:
  profiles:
    active: dev
  application:
    name: zealsay
  main:
    allow-bean-definition-overriding: true #当遇到相同的名字，是否允许覆盖
management:
  health:
    rabbit:
      enabled: false

jwt:
  header: Authorization




mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mappings/*Mapper.xml
  mapper-locations: classpath:/mappings/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.pilipa.notification.entity
  global-config:
    banner: false
    db-config:
      #驼峰下划线转换
      table-underline: true
      #mp2.3+ 全局表前缀 mp_
      #table-prefix: mp_
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      # sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      #字段验证策略之 insert 默认NOT_NULL
      insert-strategy: default
      #字段验证策略之 update 默认NOT_NULL
      update-strategy: not_null
      #字段验证策略之 select 默认NOT_NULL
      select-strategy: default
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

ignore:
  urls:
    - /api/v1/authentication/login
    - /api/v1/authentication/require
    - /api/v1/authentication/logout
    - /api/v1/oauth/**
    - /api/v1/data/index
    - /api/v1/data/article/*
    - /api/v1/data/user/*
    - /api/v1/service/hitokoto
    - /api/v1/article/c/page
    - /api/v1/article/category
    - /api/v1/article/label/page
    - /api/v1/article/read/*
    - /api/v1/article/*
    - /api/v1/comment/thumb/*
    - /api/v1/friend/link/page
    - /api/v1/user/use/username/*
    - /api/v1/user/use/email/*
    - /api/v1/user/register/email
    - /api/v1/user/confirm/email
    - /api/v1/user/register
    - /**/*.css
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /mobile/token
    - /v2/**
    - /webjars/**
    - /swagger-resources
    - /doc.html
